project:
  type: website

website:
  title: "Bosques"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/loopita/Boskes

format:
  html: default
  docx: default
  
theme: cosmo
css: styles.css

editor: source
